// Code generated by command: go run gen_amd64.go -out D:/projects/quant1x/x/simd/b8x32_amd64.s -stubs D:/projects/quant1x/x/simd/b8x32_amd64.go -pkg simd. DO NOT EDIT.

package simd

//go:noescape
func b32x8_and(a []bool, b []bool, result []bool) int

//go:noescape
func b32x8_or(a []bool, b []bool, result []bool) int

//go:noescape
func b32x8_xor(a []bool, b []bool, result []bool) int

//go:noescape
func b8x32_and(a []bool, b []bool, result []bool) int
