// Code generated by command: go run gen_amd64.go -out D:/projects/quant1x/x/simd/f32x8_amd64.s -stubs D:/projects/quant1x/x/simd/f32x8_amd64.go -pkg simd. DO NOT EDIT.

package simd

// f32x8_add adds a and b, and store the results in result.
//
//go:noescape
func f32x8_add(a []float32, b []float32, result []float32) int

// f32x8_sub subs a and b, and store the results in result.
//
//go:noescape
func f32x8_sub(a []float32, b []float32, result []float32) int

// f32x8_mul muls a and b, and store the results in result.
//
//go:noescape
func f32x8_mul(a []float32, b []float32, result []float32) int

// f32x8_div divs a and b, and store the results in result.
//
//go:noescape
func f32x8_div(a []float32, b []float32, result []float32) int

// f32x8_and ands a and b, and store the results in result.
//
//go:noescape
func f32x8_and(a []float32, b []float32, result []float32) int

// f32x8_or ors a and b, and store the results in result.
//
//go:noescape
func f32x8_or(a []float32, b []float32, result []float32) int

// f32x8_xor xors a and b, and store the results in result.
//
//go:noescape
func f32x8_xor(a []float32, b []float32, result []float32) int
