//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·_mm256_mul_ps1(SB), $0-24

    MOVQ a+0(FP), DI
    MOVQ b+8(FP), SI

    LONG $0xc059f4c5             // vmulps    ymm0, ymm1, ymm0
    MOVQ AX, Float32x8+16(FP)
    RET
